In [3]:
import torch

In [35]:
# back_distrib = torch.tensor([0.0034, 0.9966])
# eval_distrib = torch.tensor([0.0069, 0.9931])

back_distrib = torch.tensor([0.0000001, 0.0000001, 0.0000001, 0.9999999])
eval_distrib = torch.tensor([0.9, 0.1, 0.1, 0.1])

log_back_distrib = back_distrib.log()
log_eval_distrib = eval_distrib.log()

print(log_back_distrib)
print(log_eval_distrib)

tensor([-1.6118e+01, -1.6118e+01, -1.6118e+01, -1.1921e-07])
tensor([-0.1054, -2.3026, -2.3026, -2.3026])


In [36]:
diff = log_back_distrib - log_eval_distrib
diff

tensor([-16.0127, -13.8155, -13.8155,   2.3026])

In [37]:
mult = back_distrib * diff
mult

tensor([-1.6013e-06, -1.3816e-06, -1.3816e-06,  2.3026e+00])

In [38]:
sum(mult)

tensor(2.3026)